### ISSUE TITLE
ObjectPool.Get 获取超时（10秒）应该从哪个方向去找问题?

### ISSUE THREAD

**Issue by lonelyxmas** [2881099/FreeRedis#134]
83226	ObjectPool.Get 获取超时（10秒）。	2023-03-07 16:29:57.443	ExceptionFilter	   at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)
at FreeRedis.RedisClient.GetDatabase(Nullable`1 index)

**Comment by 2881099** [comment]
max pool size 设置过小。

或者使用了 PipeIine 或者 Multi 没有加 using。

**Comment by 2881099** [comment]
按说的检查一下，FreeRedis 出来也有两年多了呢
