### ISSUE TITLE
Expecting fail MessageType '49,52,13,10' 

### ISSUE THREAD

**Issue by cd-linxi** [2881099/FreeRedis#152]
Expecting fail MessageType '49,52,13,10' 堆栈：   at FreeRedis.RespHelper.Resp3Reader.ReadObject(Encoding encoding)
   at FreeRedis.Internal.DefaultRedisSocket.Read(CommandPacket cmd)
   at FreeRedis.Internal.DefaultRedisSocket.TempProxyRedisSocket.Read(CommandPacket cmd)
   at FreeRedis.RedisClient.SingleTempAdapter.<>c__DisplayClass6_0`1.<AdapterCall>b__0()
   at FreeRedis.RedisClient.LogCallCtrl[T](CommandPacket cmd, Func`1 func, Boolean aopBefore, Boolean aopAfter)
   at FreeRedis.RedisClient.LogCall[T](CommandPacket cmd, Func`1 func)
   at FreeRedis.RedisClient.SingleTempAdapter.AdapterCall[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Call[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Get(String key)

**Comment by cd-linxi** [comment]
Unable to read data from the transport connection: Connection timed out.,Connection timed out 堆栈：   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at FreeRedis.RespHelper.Resp3Reader.ReadObject(Encoding encoding)
   at FreeRedis.Internal.DefaultRedisSocket.Read(CommandPacket cmd)
   at FreeRedis.Internal.DefaultRedisSocket.TempProxyRedisSocket.Read(CommandPacket cmd)
   at FreeRedis.RedisClient.SingleTempAdapter.<>c__DisplayClass6_0`1.<AdapterCall>b__0()
   at FreeRedis.RedisClient.LogCallCtrl[T](CommandPacket cmd, Func`1 func, Boolean aopBefore, Boolean aopAfter)
   at FreeRedis.RedisClient.LogCall[T](CommandPacket cmd, Func`1 func)
   at FreeRedis.RedisClient.SingleTempAdapter.AdapterCall[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Call[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.HGet(String key, String field)

**Comment by cd-linxi** [comment]
@2881099 Take a look at this problem

**Comment by 2881099** [comment]
49,52,13,10

对应的内容如下：

```
14\r\n
```


Expecting fail MessageType '49,52,13,10' 这类信息是 resp 协议错误，服务器应该返回 $，但是返回了 1

请说明一下环境：

- redis-server 版本
- FreeRedis 版本
- 执行 HGet 命令 key field
- redis 中 hget key field 的值

**Comment by cd-linxi** [comment]
I'm sorry, it's my own negligence,
