### ISSUE TITLE
GetDatabase这个方法好像有问题？

### ISSUE THREAD

**Issue by suc8899** [2881099/FreeRedis#179]
异常信息:
System.TimeoutException: 【xxx.xxx.221.40:6379/0】ObjectPool.Get() timeout 10 seconds, see: https://github.com/dotnetcore/FreeSql/discussions/1081

   at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)

   at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)

   at FreeRedis.RedisClient.GetDatabase(Nullable`1 index)
调用方法:_redisClient.GetDatabase(15)

**Comment by 2881099** [comment]
尽量别用，除非每次都 using

**Comment by eveloki** [comment]
freeredis中的连接池实现用的是freesql的 ，我不知道你是什么场景下？大量调用GetDatabase然后没有使用using释放么
