### ISSUE TITLE
连接池整个不可用是否恰当？

### ISSUE THREAD

**Issue by xiaolipro** [2881099/FreeRedis#199]
# 1 异常堆栈

😭 轨迹中台测试环境异常_Error

cap-msg-id：316993851092066309

System.Exception: 【redis-test.default.svc.cluster.local:6379/6】Status unavailable, waiting for recovery. Connect to redis-server(redis-test.default.svc.cluster.local:6379 -> Unspecified/redis-test.default.svc.cluster.local:6379) timeout, DEBUG: Dns.GetHostEntry(redis-test.default.svc.cluster.local)=System.Net.IPHostEntry

 ---> System.TimeoutException: Connect to redis-server(redis-test.default.svc.cluster.local:6379 -> Unspecified/redis-test.default.svc.cluster.local:6379) timeout, DEBUG: Dns.GetHostEntry(redis-test.default.svc.cluster.local)=System.Net.IPHostEntry

   at FreeRedis.Internal.DefaultRedisSocket.Connect()

   at FreeRedis.Internal.DefaultRedisSocket.Write(CommandPacket cmd)

   at FreeRedis.RedisClient.SingleInsideAdapter.<>c__DisplayClass5_0`1.<AdapterCall>b__0()

   at FreeRedis.RedisClient.LogCallCtrl[[T](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%601%20func,%20Boolean%20aopBefore,%20Boolean%20aopAfter)](CommandPacket cmd, Func`1 func, Boolean aopBefore, Boolean aopAfter)

   at FreeRedis.RedisClient.LogCall[[T](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%601%20func)](CommandPacket cmd, Func`1 func)

   at FreeRedis.RedisClient.SingleInsideAdapter.AdapterCall[[TValue](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%602%20parse)](CommandPacket cmd, Func`2 parse)

   at FreeRedis.RedisClient.Call(CommandPacket cmd)

   at FreeRedis.Internal.RedisClientPoolPolicy.PrevReheatConnectionPool(ObjectPool`1 pool, Int32 minPoolSize)

   --- End of inner exception stack trace ---

   at FreeRedis.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)

   at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)

   at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)

   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<<AdapterCallAsync>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at FreeRedis.RedisClient.LogCallAsync[[T](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%601%20func)](CommandPacket cmd, Func`1 func)

   at SJZY.Track.Application.Services.TrackPush.TrackPushCacheService.GetPushContentConfigsAsync(Int32 subSystemId, Int32 customId) in /var/lib/jenkins/workspace/trackapi-test/src/SJZY.Track.Application/Services/TrackPush/TrackPushCacheService.cs:line 24

   at SJZY.Track.Application.EventHandlers.TrackPushEventHandler.ConsumerAsync(TrackPushEvent event) in /var/lib/jenkins/workspace/trackapi-test/src/SJZY.Track.Application/EventHandlers/TrackPushEventHandler.cs:line 43

   at lambda_method987(Closure, Object)

   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()

   at DotNetCore.CAP.Internal.SubscribeInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, Object[] parameter)

   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)

# 2 猜测

### 2.2 网络问题

# 3 问题分析

此问题和业务代码木有直接关系，业务代码只是简单访问redis。

从异常来看是网络问题，找了运维看几次也没看出问题，所以只能分析freeredis源码了。

### 2.1 定位异常

直接定位到freedis核心方法Get，这是我们取得redis client的方法

![img](https://gotofreight.feishu.cn/space/api/box/stream/download/asynccode/?code=OTFmNzA3MjNlZmNkODQ5MWNhOWViNGVhODFmNmQwNzFfc2ZScmpyNmo2VW5rczZTTDlDcVVIZnVQanJMWlgzd2lfVG9rZW46U2FvZ2JwZzQxb29QZVd4cHRUWmNkNHZlbmdmXzE3MjI5NTM2OTI6MTcyMjk1NzI5Ml9WNA)

可以看见，正是因为满足UnavailableException != null，才出现了我们看见的

![img](https://gotofreight.feishu.cn/space/api/box/stream/download/asynccode/?code=YTI0NGNjNDNkMjgwNmRlM2E5NDlmZDI4NTU1ZjNiZTNfOVFpVUxvMFlUR3YzRFFzMERLZG54Z2h4VWdheDRKalZfVG9rZW46SW9PYWJ0OVVpbzlua0x4eEhma2NIb04wbjdjXzE3MjI5NTM2OTI6MTcyMjk1NzI5Ml9WNA)

我们找到赋值UnavailableException 的地方：*将对象池设置为不可用，后续 Get/GetAsync 均会报错，同时启动后台定时检查服务恢复可用*

![img](https://gotofreight.feishu.cn/space/api/box/stream/download/asynccode/?code=ZTc2NTk3MzNkZmUyM2MwYzc1YmE3ZTlkYzJjN2E3MmFfeG5HYXZmVDFDVXYzS3BHcmxMR3lUWVQ0ZmxaaXpvOXZfVG9rZW46WWNMVGJabzdIb09Ccnh4VmhvSGNTV0dQbmpiXzE3MjI5NTM2OTI6MTcyMjk1NzI5Ml9WNA)

反推引用，会发现回到了innert exception的stack底部 AdapterCall

![img](https://gotofreight.feishu.cn/space/api/box/stream/download/asynccode/?code=MTM3N2U2OWI0MTU0NzhjMTc1MzZmYjZjNjcxYTM3MDFfMWlLYTM5aURpNUg3WTd4NkVIOVpRQUtrQXh6MDFqWFpfVG9rZW46S2luQ2I1VHRJb2JYeVF4ajRTamNtcWY0bktiXzE3MjI5NTM2OTI6MTcyMjk1NzI5Ml9WNA)

### 2.2 排除连接池

通过上面的定位已经可以排除连接池嫌疑了，因为get rdc的点只有一个：GetRedisSocket。

感兴趣的自己去具体了解一下，这里稍微介绍一下free redis连接池设计：任何redis操作都要从ObjectPool Get一个rdc（RedisClient）出来

```C#
// 如果木有空闲rdc 并且 池内rdc小于MaxPoolSize（默认100）
if ((_freeObjects.TryPop(out var obj) == false || obj == null) && _allObjects.Count < Policy.PoolSize)
{
    lock (_allObjectsLock)
        // DCL 如果池内rdc数量仍然小于MaxPoolSize，则添加一个rdc到池子里去
        if (_allObjects.Count < Policy.PoolSize)
            _allObjects.Add(obj = new Object<T> { Pool = this, Id = _allObjects.Count + 1 });
}

// ...

// 如果rdc释放了 或者 rdc已经超过IdleTimeout（默认20s）未接收数据
if (obj != null && obj.Value == null ||
    obj != null && Policy.IdleTimeout > TimeSpan.Zero && DateTime.Now.Subtract(obj.LastReturnTime) > Policy.IdleTimeout)
{
    try
    {
        // 重置rdc（昂贵的）
        obj.ResetValue();
    }
    catch
    {
        Return(obj);
        throw;
    }
}
```

而池子的容量是有限的（MaxPoolSize控制），如果在某个时间内有大量的redis访问，可能导致池满

```C#
// 如果木有空闲的rdc 也无法再创建新的rdc（池满）
if (obj == null)
{
    var queueItem = new GetSyncQueueInfo();

    _getSyncQueue.Enqueue(queueItem);
    _getQueue.Enqueue(false);

    if (timeout == null) timeout = Policy.SyncGetTimeout;

    try
    {
        // 等待SyncGetTimeout（默认10s）看看rdc池会不会归还空闲rdc
        if (queueItem.Wait.Wait(timeout.Value))
            obj = queueItem.ReturnValue;
    }
    catch { }

    if (obj == null) obj = queueItem.ReturnValue;
    if (obj == null) lock (queueItem.Lock) queueItem.IsTimeout = (obj = queueItem.ReturnValue) == null;
    if (obj == null) obj = queueItem.ReturnValue;
    if (queueItem.Exception != null) throw queueItem.Exception;

    if (obj == null)
    {
        // 如果仍然获取不到rdc，throw超时
        // 但是该异常会被我们上面看见的AdapterCall捕获住，然后设置池状态为不可用
        Policy.OnGetTimeout();
        if (Policy.IsThrowGetTimeoutException)
            throw new TimeoutException($"【{Policy.Name}】ObjectPool.Get() timeout {timeout.Value.TotalSeconds} seconds, see: https://github.com/dotnetcore/FreeSql/discussions/1081");

        return null;
    }
}
```

何时归还：

1. OnGet异常，导致的主动归还（该情况会reset rdc）
   1. > 默认情况下使用pooling policy是不会出现error，致使除非return的

   2. ```C#
      // OnGet 默认实现
      if (_pool.IsAvailable)
      {
          // 如果超过60s未使用，或者socket已经断开，尝试ping
          if (DateTime.Now.Subtract(obj.LastReturnTime).TotalSeconds > 60 || obj.Value.Adapter.GetRedisSocket(null).IsConnected == false)
          {
              try
              {
                CommandPacket cmd = "PING";
                cmd.IsIgnoreAop = true;
                obj.Value.Call(cmd);
             }
              catch
              {
                  obj.ResetValue();
              }
          }
      }
      ```
2. rdc销毁时会主动归还（复用根本）
   1. ```C#
      public override IRedisSocket GetRedisSocket(CommandPacket cmd)
      {
          var poolkey = GetIdleBusKey(cmd);
          var pool = _ib.Get(poolkey);
          var cli = pool.Get();
          var rds = cli.Value.Adapter.GetRedisSocket(null);
          // 每次操作完了 主动归还
          var rdsproxy = DefaultRedisSocket.CreateTempProxy(rds, () => pool.Return(cli));
          rdsproxy._poolkey = poolkey;
          rdsproxy._pool = pool;
          return rdsproxy;
      }
      ```
3. auto-free策略（可用通过IdleTimeout控制）
   1. > 作者说的这个没用

   2. ```C#
      public void AutoFree()
      {
          if (running == false) return;
          if (UnavailableException != null) return;
      
          var list = new List<Object<T>>();
          while (_freeObjects.TryPop(out var obj))
              list.Add(obj);
          foreach (var obj in list)
          {
              if (obj != null && obj.Value == null ||
                  obj != null && Policy.IdleTimeout > TimeSpan.Zero && DateTime.Now.Subtract(obj.LastReturnTime) > Policy.IdleTimeout)
              {
                  if (obj.Value != null)
                  {
                      Return(obj, true);
                      continue;
                  }
              }
              Return(obj);
          }
      }
      ```

### 2.2 重现errormessage

排除连接池嫌疑后，目光可以回到引发异常的两行代码了

```C#
try
{
    rds.Write(cmd);
    rt = rds.Read(cmd);
}
```

不管是写还是读，内部实现都调用了Connect方法

```C#
if (IsConnected == false) Connect();

// Connect实现
public void Connect()
{
    lock (_connectLock)
    {
        ResetHost(Host);

        EndPoint endpoint = IPAddress.TryParse(_ip, out var tryip) ?
            (EndPoint)new IPEndPoint(tryip, _port) :
            new DnsEndPoint(_ip, _port);

        var localSocket = endpoint.AddressFamily == AddressFamily.InterNetworkV6 ? 
            new Socket(AddressFamily.InterNetworkV6, SocketType.Stream, ProtocolType.Tcp):
            new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

        try
        {
            var asyncResult = localSocket.BeginConnect(endpoint, null, null);
            if (!asyncResult.AsyncWaitHandle.WaitOne(ConnectTimeout, true))
            {
                var endpointString = endpoint.ToString();
                if (endpointString != $"{_ip}:{_port}") endpointString = $"{_ip}:{_port} -> {endpointString}";
                var debugString = "";
                if (endpoint is DnsEndPoint)
                {
                    try { debugString = $", DEBUG: Dns.GetHostEntry({_ip})={Dns.GetHostEntry(_ip)}"; }
                    catch (Exception ex) { debugString = $", DEBUG: {ex.Message}"; }
                }
                throw new TimeoutException($"Connect to redis-server({endpointString}) timeout{debugString}");
            }
            localSocket.EndConnect(asyncResult);
        }
        catch
        {
            ReleaseSocket(localSocket);
            throw;
        }
        //...
    }
}
```

至此我们已经还原了所有异常堆栈、message。

# 4 解决方案

修改free redis源码，我们暂时维护了自己的版本，后续可能会pr到free redis。

> 如果你的项目中已经遇到了这个问题且无法自己解决就切换我们的包吧。

# 5 总结

1. free redis连接池设计有问题，大量并发下池满了且rdc没能那么快归还，导致后续的请求没有rdc可用，抛出异常，而free redis对异常的处理非常暴力：将整个rdc池的状态设为不可用（然后在后台通过一个long task thread去扫描，默认是3s），这也就导致了我们看见的高并发下大量的上述异常
2. Free redis为了节约socket资源，做了一个空闲策略，即：IdleTimeout 时间内rdc都没被用过，rdc会被reset，也就是socket被重建，这个我认为还好，关键因素是第一点

**Comment by 2881099** [comment]
并发高连接池不够用的时候，触发的 链接池Timeout 不会导致整个链接池不可用。

并发时归还不及时导致 链接池Timeout，可能是IO问题(网络或硬盘)，解决办法可以设置更大的连接池数量，或者从根本解决io问题。

提醒：连接超时，连接池超时，是两个概念。

**Comment by xubinhua888** [comment]
> # 1 异常堆栈
> 😭 轨迹中台测试环境异常_Error
> 
> cap-msg-id：316993851092066309
> 
> System.Exception: 【redis-test.default.svc.cluster.local:6379/6】Status unavailable, waiting for recovery. Connect to redis-server(redis-test.default.svc.cluster.local:6379 -> Unspecified/redis-test.default.svc.cluster.local:6379) timeout, DEBUG: Dns.GetHostEntry(redis-test.default.svc.cluster.local)=System.Net.IPHostEntry
> 
> ---> System.TimeoutException: Connect to redis-server(redis-test.default.svc.cluster.local:6379 -> Unspecified/redis-test.default.svc.cluster.local:6379) timeout, DEBUG: Dns.GetHostEntry(redis-test.default.svc.cluster.local)=System.Net.IPHostEntry
> 
> at FreeRedis.Internal.DefaultRedisSocket.Connect()
> 
> at FreeRedis.Internal.DefaultRedisSocket.Write(CommandPacket cmd)
> 
> at FreeRedis.RedisClient.SingleInsideAdapter.<>c__DisplayClass5_0`1.b__0()
> 
> at FreeRedis.RedisClient.LogCallCtrl[[T](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%601%20func,%20Boolean%20aopBefore,%20Boolean%20aopAfter)](CommandPacket cmd, Func`1 func, Boolean aopBefore, Boolean aopAfter)
> 
> at FreeRedis.RedisClient.LogCall[[T](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%601%20func)](CommandPacket cmd, Func`1 func)
> 
> at FreeRedis.RedisClient.SingleInsideAdapter.AdapterCall[[TValue](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%602%20parse)](CommandPacket cmd, Func`2 parse)
> 
> at FreeRedis.RedisClient.Call(CommandPacket cmd)
> 
> at FreeRedis.Internal.RedisClientPoolPolicy.PrevReheatConnectionPool(ObjectPool`1 pool, Int32 minPoolSize)
> 
> --- End of inner exception stack trace ---
> 
> at FreeRedis.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
> 
> at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
> 
> at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)
> 
> at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<b__0>d.MoveNext()
> 
> --- End of stack trace from previous location ---
> 
> at FreeRedis.RedisClient.LogCallAsync[[T](https://github.com/2881099/FreeRedis/issues/CommandPacket%20cmd,%20Func%601%20func)](CommandPacket cmd, Func`1 func)
> 
> at SJZY.Track.Application.Services.TrackPush.TrackPushCacheService.GetPushContentConfigsAsync(Int32 subSystemId, Int32 customId) in /var/lib/jenkins/workspace/trackapi-test/src/SJZY.Track.Application/Services/TrackPush/TrackPushCacheService.cs:line 24
> 
> at SJZY.Track.Application.EventHandlers.TrackPushEventHandler.ConsumerAsync(TrackPushEvent event) in /var/lib/jenkins/workspace/trackapi-test/src/SJZY.Track.Application/EventHandlers/TrackPushEventHandler.cs:line 43
> 
> at lambda_method987(Closure, Object)
> 
> at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
> 
> at DotNetCore.CAP.Internal.SubscribeInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, Object[] parameter)
> 
> at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
> 
> # 2 猜测
> ### 2.1 连接池问题
> ### 2.2 网络问题
> # 3 问题分析
> 此问题和业务代码木有直接关系，业务代码只是简单访问redis。
> 
> 从异常来看是网络问题，找了运维看几次也没看出问题，所以只能分析freeredis源码了。
> 
> ### 2.1 定位异常
> 直接定位到freedis核心方法Get，这是我们取得redis client的方法
> 
> ![img](https://camo.githubusercontent.com/cc45518ea6f191e16435fc9384b609952d3e154bc4c8210c9e4e080d85a465c7/68747470733a2f2f676f746f667265696768742e6665697368752e636e2f73706163652f6170692f626f782f73747265616d2f646f776e6c6f61642f6173796e63636f64652f3f636f64653d4f54466d4e7a41334d6a4e6c5a6d4e6b4f4451354d574e684f5756694e4756684f44466d4e6d51774e7a466663325a53636d70794e6d6f3256573572637a5a5454446c44635656495a6e5651616e4a4d576c677a64326c66564739725a573436553246765a324a775a7a5178623239515a56643463485255576d4e6b4e485a6c626d646d587a45334d6a49354e544d324f5449364d5463794d6a6b314e7a49354d6c39574e41)
> 
> 可以看见，正是因为满足UnavailableException != null，才出现了我们看见的
> 
> ![img](https://camo.githubusercontent.com/87a47708bc9d8bf4da8456130f66e211d8dfac0a0a0a9be8d20203e31efee512/68747470733a2f2f676f746f667265696768742e6665697368752e636e2f73706163652f6170692f626f782f73747265616d2f646f776e6c6f61642f6173796e63636f64652f3f636f64653d595449304e474e6a4e444e6b4d6a67774e6d526c4d3245354e446c6d5a4449344e5455315a6a4e695a544e664f564670565578764d466c555233597a5246467a4d45524c5a4735345a326834565764686544524b616c5a66564739725a5734365357395059574a304f565670627a6c75613078346545686d61324e4962303477626a646a587a45334d6a49354e544d324f5449364d5463794d6a6b314e7a49354d6c39574e41)
> 
> 我们找到赋值UnavailableException 的地方：_将对象池设置为不可用，后续 Get/GetAsync 均会报错，同时启动后台定时检查服务恢复可用_
> 
> ![img](https://camo.githubusercontent.com/8de03209debbcd63a87151a65f2132f72f6fabcce1bb41b7d1c726cfb07b5906/68747470733a2f2f676f746f667265696768742e6665697368752e636e2f73706163652f6170692f626f782f73747265616d2f646f776e6c6f61642f6173796e63636f64652f3f636f64653d5a5463324e546b334d7a4e6b5a6d55794d324d77597a6331596d45335a546c6b597a4a6a4e3245334d6d46666547354859585a6d564446445658597a53334248636d784d52336c55575651305a6d7861615870764f585a66564739725a57343657574e4d56474a61627a644962303943636e6834566d687653474e5456306451626d7069587a45334d6a49354e544d324f5449364d5463794d6a6b314e7a49354d6c39574e41)
> 
> 反推引用，会发现回到了innert exception的stack底部 AdapterCall
> 
> ![img](https://camo.githubusercontent.com/b52850f6fad031f63d6894e04827c657e0292c3fff3f7ab8bc9ed4ce14be82e8/68747470733a2f2f676f746f667265696768742e6665697368752e636e2f73706163652f6170692f626f782f73747265616d2f646f776e6c6f61642f6173796e63636f64652f3f636f64653d4d544d334e3255324f5749304d5455304e7a686a4d5463314d7a5a6d596a5a6a4e6a637859544d334d4446664d576c4c59544d35615552704e556733575464344e6b56494f56705251557472515868364d44467157467066564739725a57343653326c75513249315648524a62324a5965564634616a5254616d4e7463575930626b7469587a45334d6a49354e544d324f5449364d5463794d6a6b314e7a49354d6c39574e41)
> 
> ### 2.2 排除连接池
> 通过上面的定位已经可以排除连接池嫌疑了，因为get rdc的点只有一个：GetRedisSocket。
> 
> 感兴趣的自己去具体了解一下，这里稍微介绍一下free redis连接池设计：任何redis操作都要从ObjectPool Get一个rdc（RedisClient）出来
> 
> ```cs
> // 如果木有空闲rdc 并且 池内rdc小于MaxPoolSize（默认100）
> if ((_freeObjects.TryPop(out var obj) == false || obj == null) && _allObjects.Count < Policy.PoolSize)
> {
>     lock (_allObjectsLock)
>         // DCL 如果池内rdc数量仍然小于MaxPoolSize，则添加一个rdc到池子里去
>         if (_allObjects.Count < Policy.PoolSize)
>             _allObjects.Add(obj = new Object<T> { Pool = this, Id = _allObjects.Count + 1 });
> }
> 
> // ...
> 
> // 如果rdc释放了 或者 rdc已经超过IdleTimeout（默认20s）未接收数据
> if (obj != null && obj.Value == null ||
>     obj != null && Policy.IdleTimeout > TimeSpan.Zero && DateTime.Now.Subtract(obj.LastReturnTime) > Policy.IdleTimeout)
> {
>     try
>     {
>         // 重置rdc（昂贵的）
>         obj.ResetValue();
>     }
>     catch
>     {
>         Return(obj);
>         throw;
>     }
> }
> ```
> 
> 而池子的容量是有限的（MaxPoolSize控制），如果在某个时间内有大量的redis访问，可能导致池满
> 
> ```cs
> // 如果木有空闲的rdc 也无法再创建新的rdc（池满）
> if (obj == null)
> {
>     var queueItem = new GetSyncQueueInfo();
> 
>     _getSyncQueue.Enqueue(queueItem);
>     _getQueue.Enqueue(false);
> 
>     if (timeout == null) timeout = Policy.SyncGetTimeout;
> 
>     try
>     {
>         // 等待SyncGetTimeout（默认10s）看看rdc池会不会归还空闲rdc
>         if (queueItem.Wait.Wait(timeout.Value))
>             obj = queueItem.ReturnValue;
>     }
>     catch { }
> 
>     if (obj == null) obj = queueItem.ReturnValue;
>     if (obj == null) lock (queueItem.Lock) queueItem.IsTimeout = (obj = queueItem.ReturnValue) == null;
>     if (obj == null) obj = queueItem.ReturnValue;
>     if (queueItem.Exception != null) throw queueItem.Exception;
> 
>     if (obj == null)
>     {
>         // 如果仍然获取不到rdc，throw超时
>         // 但是该异常会被我们上面看见的AdapterCall捕获住，然后设置池状态为不可用
>         Policy.OnGetTimeout();
>         if (Policy.IsThrowGetTimeoutException)
>             throw new TimeoutException($"【{Policy.Name}】ObjectPool.Get() timeout {timeout.Value.TotalSeconds} seconds, see: https://github.com/dotnetcore/FreeSql/discussions/1081");
> 
>         return null;
>     }
> }
> ```
> 
> 何时归还：
> 
> 1. OnGet异常，导致的主动归还（该情况会reset rdc）
>    
>    1. > 默认情况下使用pooling policy是不会出现error，致使除非return的
>    2. ```cs
>       // OnGet 默认实现
>       if (_pool.IsAvailable)
>       {
>           // 如果超过60s未使用，或者socket已经断开，尝试ping
>           if (DateTime.Now.Subtract(obj.LastReturnTime).TotalSeconds > 60 || obj.Value.Adapter.GetRedisSocket(null).IsConnected == false)
>           {
>               try
>               {
>                 CommandPacket cmd = "PING";
>                 cmd.IsIgnoreAop = true;
>                 obj.Value.Call(cmd);
>              }
>               catch
>               {
>                   obj.ResetValue();
>               }
>           }
>       }
>       ```
> 2. rdc销毁时会主动归还（复用根本）
>    
>    1. ```cs
>       public override IRedisSocket GetRedisSocket(CommandPacket cmd)
>       {
>           var poolkey = GetIdleBusKey(cmd);
>           var pool = _ib.Get(poolkey);
>           var cli = pool.Get();
>           var rds = cli.Value.Adapter.GetRedisSocket(null);
>           // 每次操作完了 主动归还
>           var rdsproxy = DefaultRedisSocket.CreateTempProxy(rds, () => pool.Return(cli));
>           rdsproxy._poolkey = poolkey;
>           rdsproxy._pool = pool;
>           return rdsproxy;
>       }
>       ```
> 3. auto-free策略（可用通过IdleTimeout控制）
>    
>    1. > 作者说的这个没用
>    2. ```cs
>       public void AutoFree()
>       {
>           if (running == false) return;
>           if (UnavailableException != null) return;
>       
>           var list = new List<Object<T>>();
>           while (_freeObjects.TryPop(out var obj))
>               list.Add(obj);
>           foreach (var obj in list)
>           {
>               if (obj != null && obj.Value == null ||
>                   obj != null && Policy.IdleTimeout > TimeSpan.Zero && DateTime.Now.Subtract(obj.LastReturnTime) > Policy.IdleTimeout)
>               {
>                   if (obj.Value != null)
>                   {
>                       Return(obj, true);
>                       continue;
>                   }
>               }
>               Return(obj);
>           }
>       }
>       ```
> 
> ### 2.2 重现errormessage
> 排除连接池嫌疑后，目光可以回到引发异常的两行代码了
> 
> ```cs
> try
> {
>     rds.Write(cmd);
>     rt = rds.Read(cmd);
> }
> ```
> 
> 不管是写还是读，内部实现都调用了Connect方法
> 
> ```cs
> if (IsConnected == false) Connect();
> 
> // Connect实现
> public void Connect()
> {
>     lock (_connectLock)
>     {
>         ResetHost(Host);
> 
>         EndPoint endpoint = IPAddress.TryParse(_ip, out var tryip) ?
>             (EndPoint)new IPEndPoint(tryip, _port) :
>             new DnsEndPoint(_ip, _port);
> 
>         var localSocket = endpoint.AddressFamily == AddressFamily.InterNetworkV6 ? 
>             new Socket(AddressFamily.InterNetworkV6, SocketType.Stream, ProtocolType.Tcp):
>             new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
> 
>         try
>         {
>             var asyncResult = localSocket.BeginConnect(endpoint, null, null);
>             if (!asyncResult.AsyncWaitHandle.WaitOne(ConnectTimeout, true))
>             {
>                 var endpointString = endpoint.ToString();
>                 if (endpointString != $"{_ip}:{_port}") endpointString = $"{_ip}:{_port} -> {endpointString}";
>                 var debugString = "";
>                 if (endpoint is DnsEndPoint)
>                 {
>                     try { debugString = $", DEBUG: Dns.GetHostEntry({_ip})={Dns.GetHostEntry(_ip)}"; }
>                     catch (Exception ex) { debugString = $", DEBUG: {ex.Message}"; }
>                 }
>                 throw new TimeoutException($"Connect to redis-server({endpointString}) timeout{debugString}");
>             }
>             localSocket.EndConnect(asyncResult);
>         }
>         catch
>         {
>             ReleaseSocket(localSocket);
>             throw;
>         }
>         //...
>     }
> }
> ```
> 
> 至此我们已经还原了所有异常堆栈、message。
> 
> # 4 解决方案
> 修改free redis源码，我们暂时维护了自己的版本，后续可能会pr到free redis。
> 
> > 如果你的项目中已经遇到了这个问题且无法自己解决就切换我们的包吧。
> 
> # 5 总结
> 1. free redis连接池设计有问题，大量并发下池满了且rdc没能那么快归还，导致后续的请求没有rdc可用，抛出异常，而free redis对异常的处理非常暴力：将整个rdc池的状态设为不可用（然后在后台通过一个long task thread去扫描，默认是3s），这也就导致了我们看见的高并发下大量的上述异常
> 2. Free redis为了节约socket资源，做了一个空闲策略，即：IdleTimeout 时间内rdc都没被用过，rdc会被reset，也就是socket被重建，这个我认为还好，关键因素是第一点

你们修改后的包在哪里下载

**Comment by nodyang** [comment]
修改后的代码在那？

**Comment by xubinhua888** [comment]
StackExchange.Redis 有这个问题吗

**Comment by nodyang** [comment]
新的包怎么引用，我们有出现dns 解析失败。然后大面积超时

**Comment by nodyang** [comment]
{"Success":false,"Message":"【redis.time.com:6399/0】Status unavailable, waiting for recovery. Connect to redis-server(redis.time.com:6399-> Unspecifiedredis.time.com:6399) timeout, DEBUG: Dns.GetHostEntry(redis.time.com)=System.Net.IPHostEntry"}
[ELAPSED]  并发量大的时候。接口大约停顿2分钟才回复正常

**Comment by ebplayer** [comment]
我们也出现这种情况 请问新包怎么引用？ @xiaolipro

**Comment by nodyang** [comment]
> 我们也出现这种情况 请问新包怎么引用？ @xiaolipro

解决了吗？今天下午又一次崩溃了。。

**Comment by nodyang** [comment]
@xiaolipro

**Comment by RobotJohns** [comment]
> {"Success":false,"Message":"【redis.time.com:6399/0】Status unavailable, waiting for recovery. Connect to redis-server(redis.time.com:6399-> Unspecifiedredis.time.com:6399) timeout, DEBUG: Dns.GetHostEntry(redis.time.com)=System.Net.IPHostEntry"} [ELAPSED] 并发量大的时候。接口大约停顿2分钟才回复正常

后来解决了吗 我们在 高并发下也遇到 类似 问题

**Comment by RobotJohns** [comment]
八台实例， api qps 4500， 业务处理面  redis 操作就更频繁了：
“【xxxxxx.aliyuncs.com:6379/0】Status unavailable, waiting for recovery. Connect to redis-server(xxxxxx.aliyuncs.com:6379 -> Unspecified/xxxxxx.aliyuncs.com:6379) timeout, DEBUG: Dns.GetHostEntry(xxxxxx.aliyuncs.com)=System.Net.IPHostEntry
 ---> System.TimeoutException: Connect to redis-server(xxxxxx.aliyuncs.com:6379 -> Unspecified/xxxxxx.aliyuncs.com:6379) timeout, DEBUG: Dns.GetHostEntry(xxxxxx.aliyuncs.com)=System.Net.IPHostEntry
”

**Comment by 2881099** [comment]
socket 端确实连接超时了

**Comment by RobotJohns** [comment]
是不是有这个假设？ 链接池大小设置不当，造成短时间需要创建大量 socket连接. 然后创建的太多了  socket 就超时了

**Comment by 2881099** [comment]
可信任的服务端，不会瞬间创建几百个socket都不行，因为 pool size 不会太大。

至于上面说的链接池不可用，是另外的问题。

**Comment by 2881099** [comment]
那可以尝试其他sdk，如果不用单例模式，每次创建socket性能会非常低。

在局域网或者本地从不会发生这种问题。

**Comment by 2881099** [comment]
阿里云DNS解析，有时非常不稳定，看我上面发的链接。

**Comment by 2881099** [comment]
我看了 NewLifeX 的代码，它有对 DNS 本地做缓存处理，默认5分钟。

**Comment by RobotJohns** [comment]
我们经测试发现一个规律： maxpoolsize:3 , minpoolsize:1, 并发 200， 可以复现 试试看

**Comment by 2881099** [comment]
最大连接池才3个，咋并发？

**Comment by RobotJohns** [comment]
这不在定位这个错误的 关联性 和 什么东西有关

**Comment by RobotJohns** [comment]
我们把 链接 域名换成 IP直接连，就不会有上面的问题

**Comment by RobotJohns** [comment]
这如何破？ 如何改变姿势

**Comment by 2881099** [comment]
启动时预热一下，预热后会产生DNS解析缓存，后续并发请求进来的都会用缓存IP。这个缓存有效期是五分钟。

**Comment by 2881099** [comment]
预热的意思是在程序启动，请求未进来之前，使用redis对象访问任何命令，例如ping

**Comment by RobotJohns** [comment]
首先缓存IP， 每个五分钟刷新IP，刷新成功 拿到最新的IP 赋值给缓存，失败 5秒间隔刷新，直到成功，重新下一轮，

首次缓存失败  5秒间隔刷新，直到成功，重新下一轮，

**Comment by RobotJohns** [comment]
> dns解析问题
IP 也会链接超时
【172.18.77.144:6379/1】Status unavailable, waiting for recovery. Connect to redis-server(172.18.77.144:6379) timeout

**Comment by RobotJohns** [comment]
后来排查到 应该是并发太大 业务操作的时候锁等待太多，造成 进程卡死 然后操作 就会超时 链接也会超时
