### ISSUE TITLE
Expecting fail MessageType '￿'

### ISSUE THREAD

**Issue by zqlovejyc** [2881099/FreeRedis#36]
```bash
2020-12-12 16:07:14.3189 [FATAL] IdentityServer4.Hosting.IdentityServerMiddleware : Unhandled exception: 【10.32.44.29:6379/0】Expecting fail MessageType '￿' System.Exception: 【10.32.44.29:6379/0】Expecting fail MessageType '￿'
 ---> System.Net.ProtocolViolationException: Expecting fail MessageType '￿'
   at FreeRedis.Internal.AsyncRedisSocket.WriteInQueue(CommandPacket cmd)
   at FreeRedis.Internal.AsyncRedisSocket.WriteAsync(CommandPacket cmd)
   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<<AdapterCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeRedis.RedisClient.LogCallAsync[T](CommandPacket cmd, Func`1 func)
   at RedisCache`1.SetAsync(String key, T item, Int32 timeoutSeconds) in E:\Caches\RedisCache.cs:line 250
   at IdentityServer.ResponseHandling.CacheTokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request) in E:\ResponseHandling\CacheTokenResponseGenerator.cs:line 91
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at IdentityServer.Extensions.IdentityServerExtensions.<>c__DisplayClass2_0.<<UseIdentityServerOrigin>b__0>d.MoveNext() in E:\Extensions\IdentityServerExtensions.cs:line 118
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at FreeRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeRedis.RedisClient.PoolingAdapter.GetRedisSocket(CommandPacket cmd)
   at FreeRedis.Internal.AsyncRedisSocket.Manager.<>c__DisplayClass6_0.<GetAsyncRedisSocket>g__NewAsyncRedisSocket|0()
   at FreeRedis.Internal.AsyncRedisSocket.Manager.GetAsyncRedisSocket(CommandPacket cmd)
   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<<AdapterCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeRedis.RedisClient.LogCallAsync[T](CommandPacket cmd, Func`1 func)
   at RedisCache`1.SetAsync(String key, T item, Int32 timeoutSeconds) in E:\Caches\RedisCache.cs:line 250
   at IdentityServer.ResponseHandling.CacheTokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request) in E:\ResponseHandling\CacheTokenResponseGenerator.cs:line 91
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at IdentityServer.Extensions.IdentityServerExtensions.<>c__DisplayClass2_0.<<UseIdentityServerOrigin>b__0>d.MoveNext() in E:\Extensions\IdentityServerExtensions.cs:line 118
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

FreeRedis:0.2.1

**Comment by 2881099** [comment]
能提供重现步骤吗

**Comment by zqlovejyc** [comment]
这个异常是个偶发情况，在测试同时写入Redis字符串时，报了这个错误，再次测试未发现异常。

**Comment by 2881099** [comment]
这个是协议读取异常，程序内的可能情况：

- 并发使用了一个 socket 读取

抛开程序问题：

NetworkStream 读取的数据不是有效的 RESP 协议。这个情况比较复杂。

如果能重现最好了，接下来会出一个重试的参数设置，解决这个问题。

**Comment by zqlovejyc** [comment]
> 这个是协议读取异常，程序内的可能情况：
> 
> * 并发使用了一个 socket 读取
> 
> 抛开程序问题：
> 
> NetworkStream 读取的数据不是有效的 RESP 协议。这个情况比较复杂。
> 
> 如果能重现最好了，接下来会出一个重试的参数设置，解决这个问题。

这个问题的确不好重现，并不是每次都有，同样的操作时有时无，出现情况也不多，不过最近使用过程中，的确出现了多次上面的异常，然后接着会有自动恢复的日志。

**Comment by 2881099** [comment]
是程序运行中出现的吗？

redis-server 版本，单机环境，自建服务还是用的云 rds？开启了 ssl 没有？

**Comment by zqlovejyc** [comment]
> 建服务还是用的云 rds？开启了 ssl 没有？

redis-server版本：5.0.9，自建服务，没有开启ssl

**Comment by 2881099** [comment]
运行中出现，还是重启程序出现

**Comment by zqlovejyc** [comment]
> 运行中出现，还是重启程序出现

运行中偶尔出现的，运行环境时centos，.net5.0

**Comment by 2881099** [comment]
检查下 redis-server 日志，看有没有崩溃迹象。

记得之前是在某个条件下测试返回协议是错误的，类似的得到消息格式：'￿'

**Comment by 2881099** [comment]
## v0.2.3

1、增加协议解析失败，重试执行一次命令的行为

> 重试执行的担心：比如 incrby 会不会导致重复增加的问题，判断了“只读”命令才做此重试操作

2、异常信息从文本返回，变成字节数字显示（调试使用）

@zqlovejyc 升级到 0.2.3 观察一下

**Comment by 2881099** [comment]
但是我发现，日志显示的是 SetAsync 写操作的协议错误。

能否在程序内加个判断：

```c#
try
{
    await cli.SetAsync(key, xxx);
}
catch (ProtocolViolationException)
{
    var getval = cli.Get(key); //建议这个用同步方法获取
    //记录日志，检查值是否已被写入
}
```

**Comment by 2881099** [comment]
v0.2.4 增加 retry 参数遇到协议错误的时候，重试执行的次数

建议开启 retry=1 功能，再观察一下。

| 参数               | 默认值     | 说明 |
| :---------------- | --------: | :------------------- |
| protocol          | RESP2     | 若使用 RESP3 协议，你需要 Redis 6.0 环境 |
| user              | \<empty\> | Redis 服务端用户名，要求 Redis 6.0 环境 |
| password          | \<empty\> | Redis 服务端密码 |
| defaultDatabase   | 0         | Redis 服务端数据库 |
| max poolsize      | 100       | 连接池最大连接数 |
| min poolsize      | 5         | 连接池最小连接数 |
| idleTimeout       | 20000     | 连接池中元素的空闲时间（单位为毫秒 ms），适用于连接到远程服务器 |
| connectTimeout    | 10000     | 连接超时，单位为毫秒（ms） |
| receiveTimeout    | 10000     | 接收超时，单位为毫秒（ms） |
| sendTimeout       | 10000     | 发送超时，单位为毫秒（ms） |
| encoding          | utf-8     | 字符串字符集 |
| retry             | 0         | 协议发生错误时，重试执行的次数 |
| ssl               | false     | 启用加密传输 |
| name              | \<empty\> | 连接名，使用 CLIENT LIST 命令查看 |
| prefix            | \<empty\> | `key` 前辍，所有方法都会附带此前辍，cli.Set(prefix + "key", 111); |

**Comment by zqlovejyc** [comment]
> ## v0.2.4
> 增加 retry 参数遇到协议错误的时候，重试执行的次数
> 
> 建议开启 retry=1 功能，再观察一下。
> 
> 参数	默认值	说明
> protocol	RESP2	若使用 RESP3 协议，你需要 Redis 6.0 环境
> user	<empty>	Redis 服务端用户名，要求 Redis 6.0 环境
> password	<empty>	Redis 服务端密码
> defaultDatabase	0	Redis 服务端数据库
> max poolsize	100	连接池最大连接数
> min poolsize	5	连接池最小连接数
> idleTimeout	20000	连接池中元素的空闲时间（单位为毫秒 ms），适用于连接到远程服务器
> connectTimeout	10000	连接超时，单位为毫秒（ms）
> receiveTimeout	10000	接收超时，单位为毫秒（ms）
> sendTimeout	10000	发送超时，单位为毫秒（ms）
> encoding	utf-8	字符串字符集
> **retry**	**0**	**协议发生错误时，重试执行的次数**
> ssl	false	启用加密传输
> name	<empty>	连接名，使用 CLIENT LIST 命令查看
> prefix	<empty>	`key` 前辍，所有方法都会附带此前辍，cli.Set(prefix + "key", 111);

我升级到最新版本观察下，是否还会出现上面的异常，谢谢

**Comment by 2881099** [comment]
@zqlovejyc 记得连接串加上 retry=1

**Comment by zqlovejyc** [comment]
> @zqlovejyc 记得连接串加上 retry=1

已经添加上了

**Comment by zqlovejyc** [comment]
> > @zqlovejyc 记得连接串加上 retry=1
> 
> 已经添加上了

`2020-12-15 15:24:08.9622 [Fatal] [0] IdentityServer4.Hosting.IdentityServerMiddleware.Invoke : Unhandled exception: The operation is not allowed on non-connected sockets. System.IO.IOException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, Boolean ownsSocket)
   at FreeRedis.Internal.DefaultRedisSocket.Connect()
   at FreeRedis.Internal.DefaultRedisSocket.TempProxyRedisSocket.Connect()
   at FreeRedis.Internal.AsyncRedisSocket.WriteInQueue(CommandPacket cmd)
   at FreeRedis.Internal.AsyncRedisSocket.WriteAsync(CommandPacket cmd)
   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<<AdapterCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeRedis.RedisClient.LogCallAsync[T](CommandPacket cmd, Func`1 func)
   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<<AdapterCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeRedis.RedisClient.LogCallAsync[T](CommandPacket cmd, Func`1 func)
   at Caches.RedisCache`1.GetAsync(String key) in E:\Git\Core\Core\Caches\RedisCache.cs:line 185
   at IdentityServer.Validator.IntrospectionRequestValidator.ValidateAsync(NameValueCollection parameters, ApiResource api) in E:\Git\Core\IdentityServer\Validator\IntrospectionRequestValidator.cs:line 85
   at IdentityServer4.Endpoints.IntrospectionEndpoint.ProcessIntrospectionRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.IntrospectionEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at IdentityServer.Extensions.IdentityServerExtensions.<>c__DisplayClass2_0.<<UseIdentityServerOrigin>b__0>d.MoveNext() in E:\Git\Core\IdentityServer\Extensions\IdentityServerExtensions.cs:line 118
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

换成v0.2.4 出现上面的错误，暂未出现之前的错误

**Comment by zqlovejyc** [comment]
`2020-12-15 15:24:08.9622 [Fatal] [0] IdentityServer4.Hosting.IdentityServerMiddleware.Invoke : Unhandled exception: The operation is not allowed on non-connected sockets. System.IO.IOException: The operation is not allowed on non-connected sockets. at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, Boolean ownsSocket) at FreeRedis.Internal.DefaultRedisSocket.Connect() at FreeRedis.Internal.DefaultRedisSocket.TempProxyRedisSocket.Connect() at FreeRedis.Internal.AsyncRedisSocket.WriteInQueue(CommandPacket cmd) at FreeRedis.Internal.AsyncRedisSocket.WriteAsync(CommandPacket cmd) at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_01.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
at FreeRedis.RedisClient.LogCallAsync[T](CommandPacket cmd, Func1 func) at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_01.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
at FreeRedis.RedisClient.LogCallAsync[T](CommandPacket cmd, Func1 func) at Caches.RedisCache1.GetAsync(String key) in E:\Git\Core\Core\Caches\RedisCache.cs:line 185
at IdentityServer.Validator.IntrospectionRequestValidator.ValidateAsync(NameValueCollection parameters, ApiResource api) in E:\Git\Core\IdentityServer\Validator\IntrospectionRequestValidator.cs:line 85
at IdentityServer4.Endpoints.IntrospectionEndpoint.ProcessIntrospectionRequestAsync(HttpContext context)
at IdentityServer4.Endpoints.IntrospectionEndpoint.ProcessAsync(HttpContext context)
at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
at IdentityServer.Extensions.IdentityServerExtensions.<>c__DisplayClass2_0.<b__0>d.MoveNext() in E:\Git\Core\IdentityServer\Extensions\IdentityServerExtensions.cs:line 118
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)`

升级到v0.2.4版本，出现了上面的错误，暂未出现上面的异常。

**Comment by NMSAzulX** [comment]
@2881099 这个问题应该是NetworkStream在初始化时，套接字没有成功建立连接：
```C#
if (!socket.Connected)
{
   throw new IOException(SR.net_notconnected);
}
```  

建议：
1、搜集建立套接字异常的信息。
2、排查网络带宽，网络延迟，服务器资源利用率(不知是否方便提供峰值的吞吐量、链接数、资源利用率等情况)。
3、延迟等待套接字建立完成。

**Comment by zqlovejyc** [comment]
> @2881099 这个问题应该是NetworkStream在初始化时，套接字没有成功建立连接：
> 
> ```cs
> if (!socket.Connected)
> {
>    throw new IOException(SR.net_notconnected);
> }
> ```
> 
> 建议：
> 1、搜集建立套接字异常的信息。
> 2、排查网络带宽，网络延迟，服务器资源利用率(不知是否方便提供峰值的吞吐量、链接数、资源利用率等情况)。
> 3、延迟等待套接字建立完成。

程序不是刚开始的时候 出错的，运行了有一段时间了，然后就出现这个问题了，说明肯定不是初始化的时候有问题，如果是初始化的时候，那么刚开始的时候就会报错。

**Comment by 2881099** [comment]
@zqlovejyc 

1、retry 参数运行多久出现 The operation is not allowed on non-connected sockets.  错误

2、出现错误后的后续日志还有哪些

3、总共出现了多少次该错误

-------


```c#
public void Connect()
{
    ResetHost(Host);

    IPEndPoint endpoint = IPAddress.TryParse(_ip, out var tryip) ?
        new IPEndPoint(tryip, _port) :
        new IPEndPoint(Dns.GetHostAddresses(_ip).FirstOrDefault() ?? IPAddress.Parse(_ip), _port);
    var localSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

    var asyncResult = localSocket.BeginConnect(endpoint, null, null);
    if (!asyncResult.AsyncWaitHandle.WaitOne(ConnectTimeout, true))
        throw new TimeoutException("Connect to redis-server timeout");
    _socket = localSocket;
    _stream = new NetworkStream(Socket, true);
    _socket.ReceiveTimeout = (int)ReceiveTimeout.TotalMilliseconds;
    _socket.SendTimeout = (int)SendTimeout.TotalMilliseconds;
    Connected?.Invoke(this, new EventArgs());
}
```

根据错误堆栈定位的代码如上，按道理不应该出现该错。

疑点：怀疑另一种可能，异步方法的 retry 逻辑并发执行 Connect 方法的可能。

协助：因为异步的逻辑的特殊性，能否将使用的方法先修改为同步方法，如 SetAsync 改成 Set 方法，再观察。

感谢！

**Comment by zqlovejyc** [comment]
> @zqlovejyc
> 
> 1、retry 参数运行多久出现 The operation is not allowed on non-connected sockets. 错误
> 
> 2、出现错误后的后续日志还有哪些
> 
> 3、总共出现了多少次该错误
> 
> ```cs
> public void Connect()
> {
>     ResetHost(Host);
> 
>     IPEndPoint endpoint = IPAddress.TryParse(_ip, out var tryip) ?
>         new IPEndPoint(tryip, _port) :
>         new IPEndPoint(Dns.GetHostAddresses(_ip).FirstOrDefault() ?? IPAddress.Parse(_ip), _port);
>     var localSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
> 
>     var asyncResult = localSocket.BeginConnect(endpoint, null, null);
>     if (!asyncResult.AsyncWaitHandle.WaitOne(ConnectTimeout, true))
>         throw new TimeoutException("Connect to redis-server timeout");
>     _socket = localSocket;
>     _stream = new NetworkStream(Socket, true);
>     _socket.ReceiveTimeout = (int)ReceiveTimeout.TotalMilliseconds;
>     _socket.SendTimeout = (int)SendTimeout.TotalMilliseconds;
>     Connected?.Invoke(this, new EventArgs());
> }
> ```
> 
> 根据错误堆栈定位的代码如上，按道理不应该出现该错。
> 
> 疑点：怀疑另一种可能，异步方法的 retry 逻辑并发执行 Connect 方法的可能。
> 
> 协助：因为异步的逻辑的特殊性，能否将使用的方法先修改为同步方法，如 SetAsync 改成 Set 方法，再观察。
> 
> 感谢！

重新发布代码后，大概有几个小时出现上述错误，然后一直就没有恢复，GetAsync无法读取数据，后面一直提示上面的错误，我现在改成同步方法试试

**Comment by zqlovejyc** [comment]
`2020-12-16 10:02:25.3585 [Error] [0] Grpc.RetryFilter+<SendAsync>d__2.MoveNext : Grpc client request IUserService/CheckIsAdministrator exception Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="System.Net.ProtocolViolationException: Expecting fail MessageType '-1,'
   at FreeRedis.RespHelper.Resp3Reader.ReadObject(Encoding encoding)
   at FreeRedis.Internal.DefaultRedisSocket.Read(CommandPacket cmd)
   at FreeRedis.Internal.DefaultRedisSocket.TempProxyRedisSocket.Read(CommandPacket cmd)
   at FreeRedis.Internal.AsyncRedisSocket.WriteInQueue(CommandPacket cmd)
   at FreeRedis.Internal.AsyncRedisSocket.WriteAsync(CommandPacket cmd)
   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<<AdapterCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass10_0`1.<<AdapterCallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FreeRedis.RedisClient.LogCallAsync[T](CommandPacket cmd, Func`1 func)
   at Services.UserCenter.Service.UserService.GetEntityAsync(UserQueryInput input, Boolean master) in D:\LuxCode\Baize\Services\UserCenter\Service\UserService.cs:line 482
   at Services.UserCenter.Service.UserService.CheckIsAdministrator(UserQueryInput input, Boolean master) in D:\LuxCode\Baize\Services\UserCenter\Service\UserService.cs:line 495
   at MagicOnion.Server.MethodHandlerResultHelper.SerializeUnaryResult[T](UnaryResult`1 result, ServiceContext context)
   at MagicOnion.Server.MethodHandler.UnaryServerMethod[TRequest,TResponse](Byte[] request, ServerCallContext context)
")
   at MagicOnion.Client.ResponseContext`1.Deserialize()
   at MagicOnion.Client.ResponseContext`1.WaitResponseAsync()
   at Grpc.RetryFilter.SendAsync(RequestContext context, Func`2 next)`

现在频繁报上面的异常

**Comment by 2881099** [comment]
Expecting fail MessageType '-1,'

RedisClient 是使用的单例吗？

**Comment by zqlovejyc** [comment]
> Expecting fail MessageType '-1,'
> 
> RedisClient 是使用的单例吗？

![image](https://user-images.githubusercontent.com/19462884/102304342-36172f00-3f98-11eb-87c1-610f97604cd5.png)

**Comment by 2881099** [comment]
Expecting fail MessageType '-1,'

大概是使用的 Socket 被释放了，读到的数据就是 -1

v0.2.5 主要更新内容是为了支持集群模式的【客户端缓存】，顺便增加 socket 的调整：

- 忽略 读取到的 -1 消息
- Connect/ReleaseSocket 增加 lock 锁

可以更新到 v0.2.5 试试，如果影响到了生产，建议改成同步先解决问题

**Comment by zqlovejyc** [comment]
> Expecting fail MessageType '-1,'
> 
> 大概是使用的 Socket 被释放了，读到的数据就是 -1
> 
> v0.2.5 主要更新内容是为了支持集群模式的【客户端缓存】，顺便增加 socket 的调整：
> 
> * 忽略 读取到的 -1 消息
> * Connect/ReleaseSocket 增加 lock 锁
> 
> 可以更新到 v0.2.5 试试，如果影响到了生产，建议改成同步先解决问题

好的 ，谢谢

**Comment by NMSAzulX** [comment]
@2881099 我想这是通信模块相关的问题，我将打上标记，以方便复盘。

**Comment by 2881099** [comment]
@zqlovejyc 期待反馈

**Comment by zqlovejyc** [comment]
> @zqlovejyc 期待反馈

不好意思，由于我们这是正式环境，所以为了追求稳定，暂时切换到了CsRedis，待FreeRedis稳定后，再考虑重新切换回来，加油！
