### ISSUE TITLE
在Stream 队列 为 空时 调用 Xpending (key,group) 出现空指针

### ISSUE THREAD

**Issue by PSC-F** [2881099/FreeRedis#92]
`System.NullReferenceException: Object reference not set to an instance of an object.
   at FreeRedis.RedisResultThrowOrValueExtensions.<>c.<ThrowOrValueToXPending>b__2_0(Object[] a, Boolean _)
   at FreeRedis.RedisResult.ThrowOrValue[TValue](Func`3 value)
   at FreeRedis.RedisResultThrowOrValueExtensions.ThrowOrValueToXPending(RedisResult rt)
   at FreeRedis.RedisClient.<>c.<XPending>b__379_0(RedisResult rt)
   at FreeRedis.RedisClient.PoolingAdapter.<>c__DisplayClass9_0`1.<AdapterCall>b__0()
   at FreeRedis.RedisClient.LogCall[T](CommandPacket cmd, Func`1 func)
   at FreeRedis.RedisClient.PoolingAdapter.AdapterCall[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.Call[TValue](CommandPacket cmd, Func`2 parse)
   at FreeRedis.RedisClient.XPending(String key, String group)`

**Comment by PSC-F** [comment]
调用方式 

`
 var stream_entries = csredis.XReadGroup(Redis.GROUP_KEY, Redis.STREAM_KEY, 100, 5000,
                   true ,Redis.STREAM_KEY, Redis.READ_GROUP_FLAG);
                if (stream_entries.Length == 0)
                {
                    var pdXPending = csredis.XPending(Redis.STREAM_KEY, Redis.GROUP_KEY);
}
`

**Comment by 2881099** [comment]
请提供下测试数据，用代码提供

**Comment by PSC-F** [comment]
[TestDemo.tar.gz](https://github.com/2881099/FreeRedis/files/8536865/TestDemo.tar.gz)

**Comment by 2881099** [comment]
v0.5.1
